name: dice_bear
description: DiceBear API wrapper. DiceBear is an avatar library for designers and developers. Generate random avatar profile pictures!
version: 0.1.5
homepage: https://github.com/ZaifSenpai/dice_bear

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ">=2.0.5 <3.0.0"
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
